import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./styles.css';
const url=import.meta.env.VITE_SUPABASE_URL as string|undefined,key=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined;const sb=url&&key?createClient(url,key):null;
type Q={id:string;stem:string;status:string;difficulty:number;category:string|null;points:number;created_at:string};type R={id:string;round_number:number;title:string;status:string};
async function rpc(n:string,a:Record<string,unknown>={}){if(!sb)throw Error('Supabase environment not configured');const{data,error}=await sb.rpc(n,a);if(error)throw error;return data}
function App(){const[q,setQ]=useState<Q[]>([]),[rounds,setRounds]=useState<R[]>([]),[sel,setSel]=useState<Q|null>(null),[search,setSearch]=useState(''),[selectedRound,setSelectedRound]=useState<R|null>(null),[assigned,setAssigned]=useState<string[]>([]),[status,setStatus]=useState('Ready');const[draft,setDraft]=useState({stem:'',category:'',difficulty:3,points:10,options:['','','',''],correct:0,explanation:''});
 const load=async()=>{if(!sb){setStatus('Configure Supabase environment');return}const[a,b]=await Promise.all([sb.from('questions').select('id,stem,status,difficulty,category,points,created_at').order('created_at',{ascending:false}),sb.from('rounds').select('id,round_number,title,status').order('round_number')]);if(a.error||b.error){setStatus((a.error||b.error)!.message);return}setQ(a.data??[]);setRounds(b.data??[])};const loadAssigned=async(r:R)=>{if(!sb)return;const{x,error}=await sb.from('round_questions').select('question_id').eq('round_id',r.id).order('question_order');if(error){setStatus(error.message);return}setAssigned((x??[]).map((z:any)=>z.question_id))};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>q.filter(x=>x.status==='approved'&&(x.stem.toLowerCase().includes(search.toLowerCase())||String(x.category??'').toLowerCase().includes(search.toLowerCase()))),[q,search]);
 const save=async()=>{try{setStatus('Saving…');if(!sb)throw Error('Supabase not configured');const{x,error}=await sb.from('questions').insert({stem:draft.stem,status:'draft',difficulty:draft.difficulty,category:draft.category||null,points:draft.points}).select().single();if(error)throw error;const{error:oe}=await sb.from('question_options').insert(draft.options.map((text,i)=>({question_id:x.id,text,is_correct:i===draft.correct})));if(oe)throw oe;setStatus('Question saved');setDraft({stem:'',category:'',difficulty:3,points:10,options:['','','',''],correct:0,explanation:''});load()}catch(e){setStatus(e instanceof Error?e.message:String(e))}};
 const approve=async()=>{if(!sel||!sb)return;try{setStatus('Approving…');const{error}=await sb.from('questions').update({status:'approved'}).eq('id',sel.id);if(error)throw error;setStatus('Approved');load()}catch(e){setStatus(e instanceof Error?e.message:String(e))}};
 const assign=async(id:string)=>{if(!selectedRound)return;if(assigned.includes(id)){setStatus('Question already assigned');return}if(assigned.length>=3){setStatus('Round already has 3 questions');return}try{setStatus('Assigning…');await rpc('assign_question_to_round',{p_round_id:selectedRound.id,p_question_id:id,p_question_order:assigned.length+1});setAssigned([...assigned,id]);setStatus('Question assigned')}catch(e){setStatus(e instanceof Error?e.message:String(e))}};
 const remove=async(id:string)=>{if(!selectedRound)return;try{setStatus('Removing…');await rpc('remove_question_from_round',{p_round_id:selectedRound.id,p_question_id:id});const z=assigned.filter(x=>x!==id);setAssigned(z);setStatus('Removed')}catch(e){setStatus(e instanceof Error?e.message:String(e))}};
 const lock=async()=>{if(!selectedRound)return;try{setStatus('Locking round…');await rpc('lock_round_question_set',{p_round_id:selectedRound.id});setStatus('Question set locked');load()}catch(e){setStatus(e instanceof Error?e.message:String(e))}};
 return <div className="app"><header><div><small>GERiCARE • QUESTION MANAGEMENT</small><h1>Question Editor</h1></div><span>{status}</span></header><main><aside><div className="bar"><h3>Approved Question Bank</h3><input placeholder="Search questions…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{filtered.map(x=><button className={'q '+(sel?.id===x.id?'sel':'')} key={x.id} onClick={()=>setSel(x)}><b>{x.status}</b><strong>{x.stem}</strong><small>{x.category??'Uncategorised'} · D{x.difficulty} · {x.points} pts</small></button>)}</aside><section><div className="card"><h2>Create / Review</h2>{sel?<><div className="preview"><small>STATUS</small><b>{sel.status}</b><h3>{sel.stem}</h3><p>Difficulty {sel.difficulty} · {sel.points} points</p></div><button className="primary" onClick={approve} disabled={sel.status==='approved'}>{sel.status==='approved'?'Approved':'Approve Question'}</button></>:<><textarea placeholder="Question stem" value={draft.stem} onChange={e=>setDraft({...draft,stem:e.target.value})}/><div className="opts">{draft.options.map((o,i)=><div className="option" key={i}><input type="radio" checked={draft.correct===i} onChange={()=>setDraft({...draft,correct:i})}/><input placeholder={`Option ${String.fromCharCode(65+i)}`} value={o} onChange={e=>{const z=[...draft.options];z[i]=e.target.value;setDraft({...draft,options:z})}}/></div>)}</div><div className="fields"><input placeholder="Category" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/><label>Difficulty <input type="number" min="1" max="5" value={draft.difficulty} onChange={e=>setDraft({...draft,difficulty:+e.target.value})}/></label><label>Points <input type="number" value={draft.points} onChange={e=>setDraft({...draft,points:+e.target.value})}/></label></div><textarea placeholder="Explanation (optional)" value={draft.explanation} onChange={e=>setDraft({...draft,explanation:e.target.value})}/><button className="primary" onClick={save}>Save Draft</button></>}</div>
 <div className="card"><h2>Round Builder</h2><div className="rounds">{rounds.map(r=><button className={'round '+(selectedRound?.id===r.id?'sel':'')} key={r.id} onClick={()=>{setSelectedRound(r);loadAssigned(r)}}><b>R{r.round_number}</b><span>{r.title}</span><small>{r.status}</small><em>{r.status==='locked'?'LOCKED':`${assigned.length} / 3 selected`}</em></button>)}</div>{selectedRound&&<><h3>Selected questions</h3>{assigned.map((id,i)=><div className="assigned" key={id}><b>{i+1}</b><span>{q.find(x=>x.id===id)?.stem??id}</span><button onClick={()=>remove(id)} disabled={selectedRound.status==='locked'}>Remove</button></div>)}<div className="builder-actions"><button className="primary" disabled={assigned.length!==3||selectedRound.status==='locked'} onClick={lock}>Lock 3-question set</button></div></>}</div></section></main></div>};createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
