import {createClient} from '@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL as string|undefined;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined;
const configuredEvent=import.meta.env.VITE_EVENT_ID as string|undefined;
const root=document.getElementById('root')!;
function shell(title:string,body:string){root.innerHTML=`<div style="min-height:100vh;display:grid;place-items:center;background:#f5f7fa;font-family:Inter,system-ui,sans-serif;color:#172033;padding:20px"><div style="width:min(440px,100%);background:#fff;border:1px solid #e4e8ef;border-radius:18px;padding:26px;box-shadow:0 12px 32px rgba(15,23,42,.08)"><div style="font-size:11px;font-weight:800;letter-spacing:.12em;color:#6b7280">GERiCARE • SUPER ADMIN</div><h1 style="font-size:26px;margin:8px 0 18px">${title}</h1>${body}</div></div>`}
if(!url||!key){shell('Quiz Timers','<p>Supabase is not configured.</p>');throw Error('Supabase not configured')}
const sb=createClient(url,key);
async function login(){shell('Quiz Timers','<p>Sign in with a super-admin email.</p><form id="f" style="display:grid;gap:12px"><input id="email" type="email" required placeholder="Email address" style="padding:12px;border:1px solid #d8dee8;border-radius:10px;font:inherit"/><button style="padding:12px;border:0;border-radius:10px;background:#172033;color:white;font-weight:800">Send verification code</button></form><p id="s"></p>');(document.getElementById('f') as HTMLFormElement).onsubmit=async e=>{e.preventDefault();const email=(document.getElementById('email') as HTMLInputElement).value.trim();const{error}=await sb.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error){document.getElementById('s')!.textContent=error.message;return}shell('Enter verification code',`<form id="o" style="display:grid;gap:12px"><input id="otp" inputmode="numeric" maxlength="6" placeholder="6-digit code" style="padding:12px;border:1px solid #d8dee8;border-radius:10px;font:inherit;font-size:22px;text-align:center"/><button style="padding:12px;border:0;border-radius:10px;background:#172033;color:white;font-weight:800">Verify</button></form><p id="os"></p>`);(document.getElementById('o') as HTMLFormElement).onsubmit=async ev=>{ev.preventDefault();const token=(document.getElementById('otp') as HTMLInputElement).value.trim();const r=await sb.auth.verifyOtp({email,token,type:'email'});if(r.error){document.getElementById('os')!.textContent=r.error.message;return}void authorize()}}}
async function authorize(){const{data:{user}}=await sb.auth.getUser();if(!user){await login();return}let q=sb.from('event_admins').select('event_id,role').eq('user_id',user.id).eq('role','super_admin');if(configuredEvent)q=q.eq('event_id',configuredEvent);const{data,error}=await q.limit(1).maybeSingle();if(error||!data){shell('Access denied','<p>Quiz timers can be changed only by a super admin.</p>');return}root.innerHTML='';await import('./timing-admin.tsx')}
sb.auth.onAuthStateChange(e=>{if(e==='SIGNED_IN'||e==='INITIAL_SESSION')void authorize()});void authorize();