import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const url=import.meta.env.VITE_SUPABASE_URL as string|undefined;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined;
const supabase=url&&key?createClient(url,key):null;

type BoardRow={rank:number;name:string;score:number;total_score?:number;round_score?:number|null;prev_rank?:number|null;rank_delta?:number|null};
type MediaItem={id?:string;storage_path:string;mime_type?:string|null;alt?:string};
type DisplayState={event_id?:string;state:string;round_number?:number;title?:string;question?:string;options?:string[]|unknown;answer?:string;explanation?:string;top10?:unknown;media?:unknown};
const demo:DisplayState={state:'WAITING',title:'GERICARE Conference Quiz'};
function asArray(value:unknown):unknown[]{if(Array.isArray(value))return value;if(value&&typeof value==='object'){const o=value as Record<string,unknown>;if(Array.isArray(o.rows))return o.rows;if(Array.isArray(o.leaderboard))return o.leaderboard;if(Array.isArray(o.top10))return o.top10}return []}
function normalizeBoard(value:unknown):BoardRow[]{return asArray(value).map((row,i)=>{const r=(row&&typeof row==='object'?row:{}) as Record<string,unknown>;const rank=Number(r.rank??i+1)||i+1;const name=String(r.display_name??r.name??'Participant').trim()||'Participant';const total=Number(r.total_score??r.score??0)||0;const roundScore=r.round_score!=null?Number(r.round_score):null;const prev=r.prev_rank!=null?Number(r.prev_rank):null;const delta=r.rank_delta!=null?Number(r.rank_delta):(prev!=null?prev-rank:null);return{rank,name,score:total,total_score:total,round_score:roundScore,prev_rank:prev,rank_delta:delta}})}
function normalizeOptions(value:unknown):{key:string;text:string;correct?:boolean}[]{if(!Array.isArray(value))return [];return value.map((x,i)=>{if(typeof x==='string')return{key:String.fromCharCode(65+i),text:x};const o=(x&&typeof x==='object'?x:{}) as Record<string,unknown>;return{key:String(o.key??o.option_key??String.fromCharCode(65+i)),text:String(o.text??o.option_text??o.label??''),correct:!!(o.correct??o.is_correct)}})}
function normalizeMedia(value:unknown):MediaItem[]{if(!Array.isArray(value))return [];return value.flatMap(x=>{if(!x||typeof x!=='object')return[];const o=x as Record<string,unknown>;const p=String(o.storage_path??'');return p?[{id:o.id?String(o.id):undefined,storage_path:p,mime_type:o.mime_type?String(o.mime_type):null,alt:o.alt?String(o.alt):'Question image'}]:[]})}
function mediaUrl(eventId:string|undefined,path:string){if(!url||!eventId)return'';return `${url}/functions/v1/presentation-media?event_id=${encodeURIComponent(eventId)}&path=${encodeURIComponent(path)}`}
function currentQuestionMediaUrl(eventId:string|undefined,question:string|undefined){if(!url||!eventId||!question)return'';return `${url}/functions/v1/presentation-media?event_id=${encodeURIComponent(eventId)}&question=${encodeURIComponent(question)}`}
function isCorrect(o:{key:string;correct?:boolean},answer?:string){if(o.correct)return true;if(!answer)return false;return answer===o.key||answer.startsWith(o.key+'.')||answer.startsWith(o.key+' ')}
function moveEl(delta:number|null|undefined,prev:number|null|undefined){if(prev==null&&(delta==null||delta===0))return <span className="mv new">NEW</span>;if(delta==null||delta===0)return <span className="mv flat">—</span>;if(delta>0)return <span className="mv up">▲ {delta}</span>;return <span className="mv down">▼ {Math.abs(delta)}</span>}
function placeLabel(rank:number){if(rank===1)return'1st';if(rank===2)return'2nd';if(rank===3)return'3rd';return`#${rank}`}
function fmt(seconds:number){return seconds<60?`${seconds} sec`:seconds%60===0?`${seconds/60} min`:`${Math.floor(seconds/60)}m ${seconds%60}s`}
function MediaBlock({view}:{view:DisplayState}){const media=normalizeMedia(view.media);if(media.length)return <div style={{display:'grid',gridTemplateColumns:media.length>1?'repeat(2,minmax(0,1fr))':'1fr',gap:16,margin:'18px 0 24px'}}>{media.map((m,i)=><img key={m.id??i} src={mediaUrl(view.event_id,m.storage_path)} alt={m.alt||'Question image'} style={{width:'100%',maxHeight:'42vh',objectFit:'contain',borderRadius:18,background:'#fff',padding:6}}/>)}</div>;const inferred=currentQuestionMediaUrl(view.event_id,view.question);if(!inferred)return null;return <div style={{margin:'18px 0 24px'}}><img src={inferred} alt="Question image" onError={e=>{(e.currentTarget.parentElement as HTMLElement).style.display='none'}} style={{width:'100%',maxHeight:'42vh',objectFit:'contain',borderRadius:18,background:'#fff',padding:6}}/></div>}
function App(){
 const[view,setView]=useState<DisplayState>(demo);const[connected,setConnected]=useState(false);const[prelim,setPrelim]=useState(90);const[finalSec,setFinalSec]=useState(600);
 useEffect(()=>{if(!supabase)return;const load=async()=>{const{data,error}=await supabase.from('presentation_state').select('*').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!error&&data){setView(data as DisplayState);setConnected(true)}};void load();const poll=window.setInterval(load,2000);const ch=supabase.channel('projector-display').on('postgres_changes',{event:'*',schema:'public',table:'presentation_state'},p=>{if(p.new){setView(p.new as DisplayState);setConnected(true)}}).subscribe(s=>{if(s==='SUBSCRIBED')setConnected(true)});return()=>{window.clearInterval(poll);supabase.removeChannel(ch)}},[]);
 useEffect(()=>{if(!supabase||!view.event_id)return;let cancelled=false;const loadTimers=async()=>{let prelimValue:number|undefined,finalValue:number|undefined;const{data:row,error:rowError}=await supabase.from('events').select('settings').eq('id',view.event_id!).maybeSingle();if(!rowError&&row?.settings){const settings=row.settings as Record<string,unknown>;prelimValue=Number(settings.round_duration_seconds);finalValue=Number(settings.final_duration_seconds)}if(!Number.isFinite(prelimValue)||!Number.isFinite(finalValue)){const{data}=await supabase.rpc('get_quiz_timers',{p_event_id:view.event_id});if(data){prelimValue=Number(data.prelim_seconds);finalValue=Number(data.final_seconds)}}if(cancelled)return;if(Number.isFinite(prelimValue)&&Number(prelimValue)>0)setPrelim(Number(prelimValue));if(Number.isFinite(finalValue)&&Number(finalValue)>0)setFinalSec(Number(finalValue))};void loadTimers();const t=window.setInterval(loadTimers,3000);const onFocus=()=>void loadTimers();window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onFocus);return()=>{cancelled=true;window.clearInterval(t);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onFocus)}},[view.event_id]);
 const board=normalizeBoard(view.top10);const options=normalizeOptions(view.options);const hasCorrect=options.some(o=>isCorrect(o,view.answer));const showRoundCol=view.state==='ROUND_TOP10'&&board.some(b=>b.round_score!=null);const boardTitle=view.state==='ROUND_TOP10'?(view.round_number?`Round ${view.round_number} · Top 10`:'Round Top 10'):(view.title??'Overall Leaderboard');const boardKicker=view.state==='ROUND_TOP10'?'Round standings':'Overall standings';
 const content=()=>{switch(view.state){
 case'RULES':return <div className="stage rules-stage"><div className="kicker">GERICARE QUIZ · RULES</div><h1>How it works</h1><div className="projectorRules"><div className="ruleHero"><b>6</b><span>Preliminary rounds</span><b>3</b><span>Questions each</span><b>{fmt(prelim)}</b><span>Per round</span></div><div className="scoreStrip"><strong>+10 <small>Correct</small></strong><strong>−5 <small>Wrong</small></strong><strong>0 <small>Unanswered</small></strong></div><div className="ruleGrid"><div><h3>Answer freely</h3><p>Skip, return and change answers until you submit or time expires.</p></div><div><h3>Best 5 of 6 count</h3><p>Your best five preliminary scores determine your ranking.</p></div><div><h3>Tie-breaker</h3><p>Equal score → lower server-recorded response time ranks higher.</p></div><div><h3>Top 10 advance</h3><p>The ten highest-ranked participants qualify for the Grand Final.</p></div></div><div className="fairPlay"><b>FAIR PLAY</b><span>Stay on the quiz screen during an active round.</span><strong>1st violation → Warning · 2nd → Round terminated</strong></div><p className="ruleFoot">Scores, answers & explanations are released by the Quiz Master after each round · Grand Final timer: {fmt(finalSec)} · <b>Quiz Master’s decision is final.</b></p></div></div>;
 case'QUESTION':{const liveOnly=!options.length;return <div className="stage"><div className="kicker">{liveOnly?'Live':(view.title??(view.round_number?`Round ${view.round_number}`:'Question'))}</div>{liveOnly?<div className="hero-card"><h1 style={{whiteSpace:'pre-line',fontSize:'clamp(32px,5vw,72px)'}}>{view.question}</h1><p className="sub"><span className="pulse"/>Devices open — answer now</p></div>:<><h2 style={{whiteSpace:'pre-line'}}>{view.question}</h2><MediaBlock view={view}/><div className="options">{options.map((o,i)=><div key={i} className="opt"><span className="key">{o.key}</span><span>{o.text}</span></div>)}</div></>}</div>}
 case'ANSWER_REVEAL':return <div className="stage"><div className="kicker green">{view.title??'Review'}{view.round_number?` · Round ${view.round_number}`:''}</div><h2>{view.question}</h2><MediaBlock view={view}/><div className="options">{options.map((o,i)=>{const ok=isCorrect(o,view.answer);return <div key={i} className={'opt'+(ok?' correct':hasCorrect?' dim':'')}><span className="key">{o.key}</span><span>{o.text}</span></div>})}</div>{view.answer&&<div className="answer-bar">Correct · {view.answer}</div>}{view.explanation&&<p className="expl">{view.explanation}</p>}</div>;
 case'EXPLANATION':return <div className="stage"><div className="kicker">Explanation</div><MediaBlock view={view}/><h2>{view.explanation}</h2></div>;
 case'ROUND_TOP10':case'LEADERBOARD':return <div className="stage leaderboard-stage"><div className="kicker gold">{boardKicker}</div><h1 className="board-title">{boardTitle}</h1><p className="board-subtitle">{showRoundCol?'Round points and cumulative total':'Cumulative score across released rounds'}</p><div className={'board'+(showRoundCol?' with-round':'')}><div className="board-head"><span>Rank</span><span>Move</span><span>Participant</span>{showRoundCol&&<span className="num">Round</span>}<span className="num">Total</span></div>{board.length?board.map(x=>{const cls=x.rank===1?' top':x.rank===2?' top2':x.rank===3?' top3':'';return <div className={'board-row'+cls} key={`${x.rank}-${x.name}`}><span className="rank"><span className="rank-badge">{placeLabel(x.rank)}</span></span><span className="move">{moveEl(x.rank_delta,x.prev_rank)}</span><span className="name">{x.name}</span>{showRoundCol&&<span className="pts round">{x.round_score??0}</span>}<span className="pts total">{x.total_score??x.score}</span></div>}):<div className="empty">Standings will appear after results are released</div>}</div></div>;
 case'FINAL':return <div className="stage"><div className="kicker violet">Grand Final</div><div className="hero-card"><h1>{view.question??view.title??'Final'}</h1><p className="sub">Top 10 · {fmt(finalSec)} timer</p></div></div>;
 case'WINNER':return <div className="stage"><div className="kicker gold">Champion</div><div className="hero-card"><h1>{view.title??'Congratulations!'}</h1><p className="sub">GERICARE Conference Quiz</p></div></div>;
 default:return <div className="stage"><div className="kicker">GERICARE</div><div className="hero-card"><h1>{view.title??'Quiz will begin shortly'}</h1><p className="sub"><span className="pulse"/>Get ready on your devices</p></div></div>}}
 return <main><div className="brand">GERICARE</div><div className={'status'+(connected?' live':'')}>{connected?'LIVE':'RECONNECTING'}</div>{content()}</main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
