import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';
const url=import.meta.env.VITE_SUPABASE_URL as string|undefined,key=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined;
const supabase=url&&key?createClient(url,key):null;
type Round={id:string;round_number:number;title:string;status:string;result_release_at:string|null};
type Attempt={id:string;participant_id:string;round_id:string;status:string;score:number;started_at:string|null;deadline_at:string|null;submitted_at:string|null};
type Integrity={id:string;participant_id:string;event_type:string;created_at:string;metadata:Record<string,unknown>|null};
type Board={rank:number;participant_id:string;display_name:string;score:number;response_time_ms:number|null};
async function rpc(name:string,args:Record<string,unknown>={}){if(!supabase)throw Error('Supabase environment not configured');const {data,error}=await supabase.rpc(name,args);if(error)throw error;return data}
function App(){
 const [rounds,setRounds]=useState<Round[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]),[integrity,setIntegrity]=useState<Integrity[]>([]),[board,setBoard]=useState<Board[]>([]),[selected,setSelected]=useState<Round|null>(null),[message,setMessage]=useState('Ready'),[locked,setLocked]=useState(false);
 const load=async()=>{if(!supabase){setMessage('Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');return}const [{data:r,error:re},{data:a,error:ae},{data:i,error:ie}]=await Promise.all([supabase.from('rounds').select('id,round_number,title,status,result_release_at').order('round_number'),supabase.from('attempts').select('id,participant_id,round_id,status,score,started_at,deadline_at,submitted_at').order('started_at',{ascending:false}).limit(500),supabase.from('integrity_events').select('id,participant_id,event_type,created_at,metadata').order('created_at',{ascending:false}).limit(100)]);if(re||ae||ie){setMessage((re||ae||ie)!.message);return}setRounds(r??[]);setAttempts(a??[]);setIntegrity(i??[])};
 useEffect(()=>{load();if(!supabase)return;const ch=supabase.channel('control-room-live').on('postgres_changes',{event:'*',schema:'public',table:'rounds'},load).on('postgres_changes',{event:'*',schema:'public',table:'attempts'},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'integrity_events'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
 const action=async(label:string,fn:()=>Promise<unknown>)=>{try{setMessage(label+'…');await fn();setMessage(label+' complete');await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}};
 const control=(r:Round)=>action('Acquiring live control',async()=>{await rpc('acquire_live_control',{p_event_id:null});setSelected(r);setLocked(true)});
 const open=(r:Round)=>action('Opening round',()=>rpc('open_round',{p_round_id:r.id}));
 const close=(r:Round)=>action('Closing round',()=>rpc('close_round',{p_round_id:r.id}));
 const release=(r:Round)=>action('Releasing results',()=>rpc('release_round_results',{p_round_id:r.id}));
 const active=useMemo(()=>rounds.find(r=>r.status==='live')??selected,[rounds,selected]);
 const currentAttempts=active?attempts.filter(a=>a.round_id===active.id):attempts;
 const counts={active:currentAttempts.filter(a=>a.status==='active').length,submitted:currentAttempts.filter(a=>a.status==='submitted'||a.status==='completed').length,terminated:currentAttempts.filter(a=>a.status==='terminated').length};
 return <div className="shell"><header><div><div className="eyebrow">GERiCARE • LIVE OPERATIONS</div><h1>Control Room</h1></div><div className={locked?'lock on':'lock'}>{locked?'● LIVE CONTROL':'○ VIEW ONLY'}</div></header><main><section className="hero"><div><span className="label">CURRENT ROUND</span><h2>{active?`Round ${active.round_number} — ${active.title}`:'No active round'}</h2><p>{message}</p></div><div className="actions">{active&&<><button onClick={()=>control(active)}>Take Control</button><button onClick={()=>open(active)}>Open</button><button onClick={()=>close(active)}>Close</button><button onClick={()=>release(active)}>Release Results</button></>}</div></section><section className="grid"><div className="panel rounds"><h3>Rounds</h3>{rounds.map(r=><button className={'row '+(selected?.id===r.id?'selected':'')} key={r.id} onClick={()=>setSelected(r)}><span>R{r.round_number}</span><strong>{r.title}</strong><em>{r.status}</em></button>)}{!rounds.length&&<p className="muted">No rounds configured.</p>}</div><div className="panel"><h3>Participant Monitor</h3><div className="stats"><div><b>{counts.active}</b><span>Active</span></div><div><b>{counts.submitted}</b><span>Submitted</span></div><div><b>{counts.terminated}</b><span>Terminated</span></div></div><div className="table">{currentAttempts.slice(0,12).map(a=><div className="tr" key={a.id}><span>{a.participant_id.slice(0,8)}</span><strong>{a.status}</strong><span>{a.score} pts</span></div>)}</div></div><div className="panel"><h3>Leaderboard</h3>{board.length?<div className="table">{board.slice(0,10).map(b=><div className="tr" key={b.participant_id}><b>#{b.rank}</b><strong>{b.display_name}</strong><span>{b.score}</span></div>)}</div>:<p className="muted">Released leaderboard snapshots will appear here.</p>}</div><div className="panel"><h3>Integrity Monitor</h3>{integrity.slice(0,10).map(x=><div className="tr" key={x.id}><span>{new Date(x.created_at).toLocaleTimeString()}</span><strong>{x.event_type}</strong><span>{x.participant_id.slice(0,8)}</span></div>)}{!integrity.length&&<p className="muted">No integrity events.</p>}</div></section></main></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
