import { useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'
import QuestionImages,{type QuestionImage} from './QuestionImages'

type Option={option_key:string;text:string}
type FinalQuestion={id:string;stem:string;position:number;options:Option[]}
type FinalBundle={is_finalist:boolean;active?:boolean;rank?:number;participant_id?:string;final_attempt_id?:string;deadline_at?:string;score?:number;questions?:FinalQuestion[]}
type SuddenBundle={active:boolean;sudden_death_id?:string;question_number?:number;question_id?:string;stem?:string;options?:Option[];answered?:boolean;participant_id?:string}

function fmt(seconds:number){return seconds<60?`${seconds} seconds`:seconds%60===0?`${seconds/60} minute${seconds===60?'':'s'}`:`${Math.floor(seconds/60)} min ${seconds%60} sec`}

function Rules({eventId}:{eventId:string}){
 const[prelim,setPrelim]=useState(90),[finalSec,setFinalSec]=useState(600),[open,setOpen]=useState(false)
 useEffect(()=>{if(!supabase)return;void supabase.rpc('get_quiz_timers',{p_event_id:eventId}).then(({data})=>{if(data){setPrelim(Number(data.prelim_seconds??90));setFinalSec(Number(data.final_seconds??600))}})},[eventId])
 return <section className="card rulesCard"><div className="rulesSummary"><div><p className="eyebrow">QUIZ RULES</p><h3>Know the rules before you play</h3><p>6 preliminary rounds · 3 MCQs each · <b>{fmt(prelim)}</b> per round</p></div><button className="secondary small" onClick={()=>setOpen(v=>!v)}>{open?'Hide rules':'View rules'}</button></div>{open&&<div className="participantRules"><h3>Preliminary Rounds</h3><ol><li>The quiz consists of <b>6 preliminary rounds</b>, with <b>3 single-best-answer MCQs per round</b>.</li><li>Each round has a fixed time limit of <b>{fmt(prelim)}</b>. The timer begins when you start and the round is submitted automatically when time expires.</li><li><b>Scoring:</b> Correct +10 · Incorrect −5 · Unanswered 0.</li><li>You may skip questions, move between questions and change an answer until the round is submitted or time expires.</li><li>Once submitted, a round cannot be reopened.</li><li>Scores, correct answers and explanations become visible only after the Quiz Master releases the results.</li><li><b>Tie-breaker:</b> If scores are equal, the participant with the lower server-recorded response time ranks higher.</li><li><b>Qualification:</b> The best 5 scores from the 6 preliminary rounds determine the preliminary ranking. Response time from those qualifying rounds resolves ties.</li><li>The <b>Top 10</b> participants qualify for the Grand Final.</li></ol><h3>Fair Play</h3><p>During an active round, do not switch apps, change browser tabs, minimise the quiz or leave the quiz screen.</p><div className="integrityRule"><b>1st violation → Warning</b><span>·</span><b>2nd violation in the same round → Round terminated</b></div><p>The integrity counter resets for each new round, while integrity events remain recorded for review. Monitoring operates only while you are actively taking a round.</p><h3>Grand Final</h3><p>The Top 10 qualifiers compete in the Grand Final. The current Final timer is <b>{fmt(finalSec)}</b>. Final scoring and conduct follow the rules announced by the Quiz Master. Preliminary performance is used only where specified for tie-breaking and does not otherwise add to the Final score.</p><p className="rulesDecision"><b>The Quiz Master’s decision is final</b> in the event of a scoring, technical, integrity or tie-resolution dispute.</p></div>}</section>
}

export default function FinalPanel({eventId}:{eventId:string}){
 const[final,setFinal]=useState<FinalBundle|null>(null),[sudden,setSudden]=useState<SuddenBundle|null>(null),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[remaining,setRemaining]=useState(0),[status,setStatus]=useState(''),[media,setMedia]=useState<Record<string,QuestionImage[]>>({})
 const questions=final?.questions??[],q=questions[index]
 const load=async()=>{if(!supabase)return;const[{data:f,error:fe},{data:s,error:se}]=await Promise.all([supabase.rpc('get_my_final_bundle',{p_event_id:eventId}),supabase.rpc('get_my_sudden_death_bundle',{p_event_id:eventId})]);if(fe||se){setStatus((fe||se)!.message);return}setFinal(f as FinalBundle);setSudden(s as SuddenBundle)}
 useEffect(()=>{void load();const t=window.setInterval(load,10000);return()=>window.clearInterval(t)},[eventId])
 useEffect(()=>{if(!final?.deadline_at)return;const tick=()=>setRemaining(Math.max(0,Math.ceil((new Date(final.deadline_at!).getTime()-Date.now())/1000)));tick();const t=window.setInterval(tick,1000);return()=>window.clearInterval(t)},[final?.deadline_at])
 useEffect(()=>{const loadMedia=async()=>{if(!supabase||!q?.id||media[q.id])return;const{data:rows,error}=await supabase.from('question_media').select('id,storage_path,mime_type,metadata').eq('question_id',q.id).eq('media_type','image').order('sort_order');if(error)return;const items:QuestionImage[]=[];for(const m of rows??[]){const{data:s}=await supabase.storage.from('question-media').createSignedUrl(m.storage_path,3600);if(s?.signedUrl)items.push({id:m.id,url:s.signedUrl,mime_type:m.mime_type,alt:m.metadata?.alt??m.metadata?.original_name??'Question image'})}setMedia(v=>({...v,[q.id]:items}))};void loadMedia()},[q?.id])
 const time=useMemo(()=>`${Math.floor(remaining/60).toString().padStart(2,'0')}:${(remaining%60).toString().padStart(2,'0')}`,[remaining])
 const chooseFinal=async(option:string)=>{if(!supabase||!final?.final_attempt_id||!q)return;setStatus('');if(!answers[q.id]){const{error:b}=await supabase.rpc('begin_final_question',{p_final_attempt:final.final_attempt_id,p_question:q.id});if(b){setStatus(b.message);return}}const{error}=await supabase.rpc('submit_final_response',{p_final_attempt:final.final_attempt_id,p_question:q.id,p_option:option});if(error){setStatus(error.message);return}setAnswers(v=>({...v,[q.id]:option}))}
 const finishFinal=async()=>{if(!supabase||!final?.final_attempt_id)return;const{error}=await supabase.rpc('finish_final',{p_final_attempt:final.final_attempt_id});if(error)setStatus(error.message);else{setStatus('Grand Final submitted');await load()}}
 const chooseSudden=async(option:string)=>{if(!supabase||!sudden?.sudden_death_id||!sudden.participant_id)return;const{error}=await supabase.rpc('submit_sudden_death_response',{p_sudden_death_id:sudden.sudden_death_id,p_participant_id:sudden.participant_id,p_option:option});if(error)setStatus(error.message);else{setSudden({...sudden,answered:true});setStatus('Sudden-death answer submitted')}}
 const finalPanel=!final?.is_finalist?null:<section className="card finalCard"><p className="eyebrow">GRAND FINALIST · RANK #{final.rank??'—'}</p>{final.active&&q?<><div className="quizTop"><span>Final question {index+1} of {questions.length}</span><strong>{time}</strong></div><h2>{q.stem}</h2><QuestionImages media={media[q.id]}/><div className="options">{q.options.map(o=><button key={o.option_key} className={answers[q.id]===o.option_key?'option selected':'option'} onClick={()=>chooseFinal(o.option_key)}><b>{o.option_key}</b><span>{o.text}</span></button>)}</div><div className="nav">{questions.map((fq,i)=><button key={fq.id} className={i===index?'':'secondary'} onClick={()=>setIndex(i)}>{i+1}{answers[fq.id]?' ✓':''}</button>)}</div><div className="actions">{index>0&&<button className="secondary" onClick={()=>setIndex(i=>i-1)}>Previous</button>}{index<questions.length-1?<button onClick={()=>setIndex(i=>i+1)}>{answers[q.id]?'Next':'Skip'}</button>:<button onClick={finishFinal}>Submit Final</button>}</div></>:<p>{final.score!=null?`Final score: ${final.score}`:'The Grand Final has not started yet.'}</p>}{sudden?.active&&<div className="sudden"><p className="eyebrow">SUDDEN DEATH · QUESTION {sudden.question_number}</p><h3>{sudden.stem}</h3>{sudden.answered?<div className="notice">Answer submitted. Both finalists must answer before resolution.</div>:<div className="options">{sudden.options?.map(o=><button key={o.option_key} className="option" onClick={()=>chooseSudden(o.option_key)}><b>{o.option_key}</b><span>{o.text}</span></button>)}</div>}</div>}{status&&<div className="notice">{status}</div>}</section>
 return <><Rules eventId={eventId}/>{finalPanel}</>
}
