import { useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'

type Option={option_key:string;text:string}
type FinalQuestion={id:string;stem:string;position:number;options:Option[]}
type FinalBundle={is_finalist:boolean;active?:boolean;rank?:number;participant_id?:string;final_attempt_id?:string;deadline_at?:string;score?:number;questions?:FinalQuestion[]}
type SuddenBundle={active:boolean;sudden_death_id?:string;question_number?:number;question_id?:string;stem?:string;options?:Option[];answered?:boolean;participant_id?:string}

export default function FinalPanel({eventId}:{eventId:string}){
 const[final,setFinal]=useState<FinalBundle|null>(null),[sudden,setSudden]=useState<SuddenBundle|null>(null),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[remaining,setRemaining]=useState(0),[status,setStatus]=useState('')
 const questions=final?.questions??[],q=questions[index]
 const load=async()=>{if(!supabase)return;const[{data:f,error:fe},{data:s,error:se}]=await Promise.all([supabase.rpc('get_my_final_bundle',{p_event_id:eventId}),supabase.rpc('get_my_sudden_death_bundle',{p_event_id:eventId})]);if(fe||se){setStatus((fe||se)!.message);return}setFinal(f as FinalBundle);setSudden(s as SuddenBundle)}
 useEffect(()=>{void load();const t=window.setInterval(load,10000);return()=>window.clearInterval(t)},[eventId])
 useEffect(()=>{if(!final?.deadline_at)return;const tick=()=>setRemaining(Math.max(0,Math.ceil((new Date(final.deadline_at!).getTime()-Date.now())/1000)));tick();const t=window.setInterval(tick,1000);return()=>window.clearInterval(t)},[final?.deadline_at])
 const time=useMemo(()=>`${Math.floor(remaining/60).toString().padStart(2,'0')}:${(remaining%60).toString().padStart(2,'0')}`,[remaining])
 const chooseFinal=async(option:string)=>{if(!supabase||!final?.final_attempt_id||!q)return;setStatus('');if(!answers[q.id]){const{error:b}=await supabase.rpc('begin_final_question',{p_final_attempt:final.final_attempt_id,p_question:q.id});if(b){setStatus(b.message);return}}const{error}=await supabase.rpc('submit_final_response',{p_final_attempt:final.final_attempt_id,p_question:q.id,p_option:option});if(error){setStatus(error.message);return}setAnswers(v=>({...v,[q.id]:option}))}
 const finishFinal=async()=>{if(!supabase||!final?.final_attempt_id)return;const{error}=await supabase.rpc('finish_final',{p_final_attempt:final.final_attempt_id});if(error)setStatus(error.message);else{setStatus('Grand Final submitted');await load()}}
 const chooseSudden=async(option:string)=>{if(!supabase||!sudden?.sudden_death_id||!sudden.participant_id)return;const{error}=await supabase.rpc('submit_sudden_death_response',{p_sudden_death_id:sudden.sudden_death_id,p_participant_id:sudden.participant_id,p_option:option});if(error)setStatus(error.message);else{setSudden({...sudden,answered:true});setStatus('Sudden-death answer submitted')}}
 if(!final?.is_finalist)return null
 return <section className="card finalCard"><p className="eyebrow">GRAND FINALIST · RANK #{final.rank??'—'}</p>{final.active&&q?<><div className="quizTop"><span>Final question {index+1} of {questions.length}</span><strong>{time}</strong></div><h2>{q.stem}</h2><div className="options">{q.options.map(o=><button key={o.option_key} className={answers[q.id]===o.option_key?'option selected':'option'} disabled={!!answers[q.id]} onClick={()=>chooseFinal(o.option_key)}><b>{o.option_key}</b><span>{o.text}</span></button>)}</div><div className="actions">{index>0&&<button className="secondary" onClick={()=>setIndex(i=>i-1)}>Previous</button>}{index<questions.length-1?<button disabled={!answers[q.id]} onClick={()=>setIndex(i=>i+1)}>Next</button>:<button disabled={!answers[q.id]} onClick={finishFinal}>Submit Final</button>}</div></>:<p>{final.score!=null?`Final score: ${final.score}`:'The Grand Final has not started yet.'}</p>}{sudden?.active&&<div className="sudden"><p className="eyebrow">SUDDEN DEATH · QUESTION {sudden.question_number}</p><h3>{sudden.stem}</h3>{sudden.answered?<div className="notice">Answer submitted. Both finalists must answer before resolution.</div>:<div className="options">{sudden.options?.map(o=><button key={o.option_key} className="option" onClick={()=>chooseSudden(o.option_key)}><b>{o.option_key}</b><span>{o.text}</span></button>)}</div>}</div>}{status&&<div className="notice">{status}</div>}</section>
}
